### ISSUE TITLE
Hello, do you recommend any other hardware than HackRF1 and RTL_SDR?

### ISSUE THREAD

**Issue by RichardKCollins** [hb9tf/spectre#4]
Just saying hello.  Found a note at https://medium.com/hb9tf/rf-spectrum-analysis-open-sourced-7ec5911fc2

Are any of the knock-offs stable?

**Comment by finfinack** [comment]
Unfortunately we do not have first-hand experience with any of the copies of the original HackRF One. Since the HackRF One is open source software and hardware, in theory the copies should be equivalent but I suspect that a lot about stability and quality comes down to parts selection which may differ…

Secondly, while the HackRF One is a great tool, we have run into problems after it running for a while and we didn‘t have the time yet to investigate whether the errors originated in the HackRF and its firm- and software (as I suspect) or our software.

**Comment by RichardKCollins** [comment]
Thanks for your help.
